### ISSUE TITLE
Use a more appropriate license

### ISSUE THREAD

**Issue by goodmami** [nlposs/NLP-OSS#25]
This is not a software project so the MIT license currently in use is not really applicable. Something like a Creative Commons license would be better. I like [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) as it's like the MIT license equivalent for creative commons. [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) is more like a GPL license because it requires copyleft.

**Comment by alvations** [comment]
Agree. 

I personally like [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) and that means that people don't have to attribute us. But I think CC-BY is appropriate for this repo, just in case people abuses CC0 =)

@e9t @mhagiwara @dimazest @nelson-liu What your take on this?

**Comment by e9t** [comment]
`CC-BY` seems like a reasonable choice since it is most similar to the previous license.

I wouldn't mind converting to `CC0` though, because the main contents in the repo openly show the process of organizing a workshop, which people can refer to when they host any future workshops. It would be nice if people could freely use the contents, even without attribution.

**Comment by alvations** [comment]
Lets replace the license before we send out the first CPF =)

@e9t @mhagiwara @dimazest @nelson-liu @geetickachauhan any preference for `CC-BY` or `CC0`?

**Comment by dimazest** [comment]
Hi all,

Either are fine with me with a slight preference for cc0.

Dima

**Comment by e9t** [comment]
Let’s go for cc0!

**Comment by mhagiwara** [comment]
+1 for CC0

**Comment by geetickachauhan** [comment]
+1 for CC0!

**Comment by alvations** [comment]
We'll go CC0 then!! 

Thank you @goodmami  for bringing the license issue up!!
